package mybatis.model;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class CapitalistExample {
    /**
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * @mbg.generated
     */
    public CapitalistExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table capitalist
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("`name` is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("`name` is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("`name` =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("`name` <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("`name` >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("`name` >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("`name` <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("`name` <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("`name` like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("`name` not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("`name` in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("`name` not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("`name` between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("`name` not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andChineseNameIsNull() {
            addCriterion("chinese_name is null");
            return (Criteria) this;
        }

        public Criteria andChineseNameIsNotNull() {
            addCriterion("chinese_name is not null");
            return (Criteria) this;
        }

        public Criteria andChineseNameEqualTo(String value) {
            addCriterion("chinese_name =", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameNotEqualTo(String value) {
            addCriterion("chinese_name <>", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameGreaterThan(String value) {
            addCriterion("chinese_name >", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameGreaterThanOrEqualTo(String value) {
            addCriterion("chinese_name >=", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameLessThan(String value) {
            addCriterion("chinese_name <", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameLessThanOrEqualTo(String value) {
            addCriterion("chinese_name <=", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameLike(String value) {
            addCriterion("chinese_name like", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameNotLike(String value) {
            addCriterion("chinese_name not like", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameIn(List<String> values) {
            addCriterion("chinese_name in", values, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameNotIn(List<String> values) {
            addCriterion("chinese_name not in", values, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameBetween(String value1, String value2) {
            addCriterion("chinese_name between", value1, value2, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameNotBetween(String value1, String value2) {
            addCriterion("chinese_name not between", value1, value2, "chineseName");
            return (Criteria) this;
        }

        public Criteria andMaxQuotaIsNull() {
            addCriterion("max_quota is null");
            return (Criteria) this;
        }

        public Criteria andMaxQuotaIsNotNull() {
            addCriterion("max_quota is not null");
            return (Criteria) this;
        }

        public Criteria andMaxQuotaEqualTo(BigDecimal value) {
            addCriterion("max_quota =", value, "maxQuota");
            return (Criteria) this;
        }

        public Criteria andMaxQuotaNotEqualTo(BigDecimal value) {
            addCriterion("max_quota <>", value, "maxQuota");
            return (Criteria) this;
        }

        public Criteria andMaxQuotaGreaterThan(BigDecimal value) {
            addCriterion("max_quota >", value, "maxQuota");
            return (Criteria) this;
        }

        public Criteria andMaxQuotaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("max_quota >=", value, "maxQuota");
            return (Criteria) this;
        }

        public Criteria andMaxQuotaLessThan(BigDecimal value) {
            addCriterion("max_quota <", value, "maxQuota");
            return (Criteria) this;
        }

        public Criteria andMaxQuotaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("max_quota <=", value, "maxQuota");
            return (Criteria) this;
        }

        public Criteria andMaxQuotaIn(List<BigDecimal> values) {
            addCriterion("max_quota in", values, "maxQuota");
            return (Criteria) this;
        }

        public Criteria andMaxQuotaNotIn(List<BigDecimal> values) {
            addCriterion("max_quota not in", values, "maxQuota");
            return (Criteria) this;
        }

        public Criteria andMaxQuotaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("max_quota between", value1, value2, "maxQuota");
            return (Criteria) this;
        }

        public Criteria andMaxQuotaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("max_quota not between", value1, value2, "maxQuota");
            return (Criteria) this;
        }

        public Criteria andMinQuotaIsNull() {
            addCriterion("min_quota is null");
            return (Criteria) this;
        }

        public Criteria andMinQuotaIsNotNull() {
            addCriterion("min_quota is not null");
            return (Criteria) this;
        }

        public Criteria andMinQuotaEqualTo(BigDecimal value) {
            addCriterion("min_quota =", value, "minQuota");
            return (Criteria) this;
        }

        public Criteria andMinQuotaNotEqualTo(BigDecimal value) {
            addCriterion("min_quota <>", value, "minQuota");
            return (Criteria) this;
        }

        public Criteria andMinQuotaGreaterThan(BigDecimal value) {
            addCriterion("min_quota >", value, "minQuota");
            return (Criteria) this;
        }

        public Criteria andMinQuotaGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("min_quota >=", value, "minQuota");
            return (Criteria) this;
        }

        public Criteria andMinQuotaLessThan(BigDecimal value) {
            addCriterion("min_quota <", value, "minQuota");
            return (Criteria) this;
        }

        public Criteria andMinQuotaLessThanOrEqualTo(BigDecimal value) {
            addCriterion("min_quota <=", value, "minQuota");
            return (Criteria) this;
        }

        public Criteria andMinQuotaIn(List<BigDecimal> values) {
            addCriterion("min_quota in", values, "minQuota");
            return (Criteria) this;
        }

        public Criteria andMinQuotaNotIn(List<BigDecimal> values) {
            addCriterion("min_quota not in", values, "minQuota");
            return (Criteria) this;
        }

        public Criteria andMinQuotaBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("min_quota between", value1, value2, "minQuota");
            return (Criteria) this;
        }

        public Criteria andMinQuotaNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("min_quota not between", value1, value2, "minQuota");
            return (Criteria) this;
        }

        public Criteria andPeriodIsNull() {
            addCriterion("period is null");
            return (Criteria) this;
        }

        public Criteria andPeriodIsNotNull() {
            addCriterion("period is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodEqualTo(String value) {
            addCriterion("period =", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotEqualTo(String value) {
            addCriterion("period <>", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodGreaterThan(String value) {
            addCriterion("period >", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodGreaterThanOrEqualTo(String value) {
            addCriterion("period >=", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodLessThan(String value) {
            addCriterion("period <", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodLessThanOrEqualTo(String value) {
            addCriterion("period <=", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodLike(String value) {
            addCriterion("period like", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotLike(String value) {
            addCriterion("period not like", value, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodIn(List<String> values) {
            addCriterion("period in", values, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotIn(List<String> values) {
            addCriterion("period not in", values, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodBetween(String value1, String value2) {
            addCriterion("period between", value1, value2, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodNotBetween(String value1, String value2) {
            addCriterion("period not between", value1, value2, "period");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitIsNull() {
            addCriterion("period_unit is null");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitIsNotNull() {
            addCriterion("period_unit is not null");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitEqualTo(String value) {
            addCriterion("period_unit =", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitNotEqualTo(String value) {
            addCriterion("period_unit <>", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitGreaterThan(String value) {
            addCriterion("period_unit >", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitGreaterThanOrEqualTo(String value) {
            addCriterion("period_unit >=", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitLessThan(String value) {
            addCriterion("period_unit <", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitLessThanOrEqualTo(String value) {
            addCriterion("period_unit <=", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitLike(String value) {
            addCriterion("period_unit like", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitNotLike(String value) {
            addCriterion("period_unit not like", value, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitIn(List<String> values) {
            addCriterion("period_unit in", values, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitNotIn(List<String> values) {
            addCriterion("period_unit not in", values, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitBetween(String value1, String value2) {
            addCriterion("period_unit between", value1, value2, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andPeriodUnitNotBetween(String value1, String value2) {
            addCriterion("period_unit not between", value1, value2, "periodUnit");
            return (Criteria) this;
        }

        public Criteria andBankListIsNull() {
            addCriterion("bank_list is null");
            return (Criteria) this;
        }

        public Criteria andBankListIsNotNull() {
            addCriterion("bank_list is not null");
            return (Criteria) this;
        }

        public Criteria andBankListEqualTo(String value) {
            addCriterion("bank_list =", value, "bankList");
            return (Criteria) this;
        }

        public Criteria andBankListNotEqualTo(String value) {
            addCriterion("bank_list <>", value, "bankList");
            return (Criteria) this;
        }

        public Criteria andBankListGreaterThan(String value) {
            addCriterion("bank_list >", value, "bankList");
            return (Criteria) this;
        }

        public Criteria andBankListGreaterThanOrEqualTo(String value) {
            addCriterion("bank_list >=", value, "bankList");
            return (Criteria) this;
        }

        public Criteria andBankListLessThan(String value) {
            addCriterion("bank_list <", value, "bankList");
            return (Criteria) this;
        }

        public Criteria andBankListLessThanOrEqualTo(String value) {
            addCriterion("bank_list <=", value, "bankList");
            return (Criteria) this;
        }

        public Criteria andBankListLike(String value) {
            addCriterion("bank_list like", value, "bankList");
            return (Criteria) this;
        }

        public Criteria andBankListNotLike(String value) {
            addCriterion("bank_list not like", value, "bankList");
            return (Criteria) this;
        }

        public Criteria andBankListIn(List<String> values) {
            addCriterion("bank_list in", values, "bankList");
            return (Criteria) this;
        }

        public Criteria andBankListNotIn(List<String> values) {
            addCriterion("bank_list not in", values, "bankList");
            return (Criteria) this;
        }

        public Criteria andBankListBetween(String value1, String value2) {
            addCriterion("bank_list between", value1, value2, "bankList");
            return (Criteria) this;
        }

        public Criteria andBankListNotBetween(String value1, String value2) {
            addCriterion("bank_list not between", value1, value2, "bankList");
            return (Criteria) this;
        }

        public Criteria andLoanTimeIsNull() {
            addCriterion("loan_time is null");
            return (Criteria) this;
        }

        public Criteria andLoanTimeIsNotNull() {
            addCriterion("loan_time is not null");
            return (Criteria) this;
        }

        public Criteria andLoanTimeEqualTo(String value) {
            addCriterion("loan_time =", value, "loanTime");
            return (Criteria) this;
        }

        public Criteria andLoanTimeNotEqualTo(String value) {
            addCriterion("loan_time <>", value, "loanTime");
            return (Criteria) this;
        }

        public Criteria andLoanTimeGreaterThan(String value) {
            addCriterion("loan_time >", value, "loanTime");
            return (Criteria) this;
        }

        public Criteria andLoanTimeGreaterThanOrEqualTo(String value) {
            addCriterion("loan_time >=", value, "loanTime");
            return (Criteria) this;
        }

        public Criteria andLoanTimeLessThan(String value) {
            addCriterion("loan_time <", value, "loanTime");
            return (Criteria) this;
        }

        public Criteria andLoanTimeLessThanOrEqualTo(String value) {
            addCriterion("loan_time <=", value, "loanTime");
            return (Criteria) this;
        }

        public Criteria andLoanTimeLike(String value) {
            addCriterion("loan_time like", value, "loanTime");
            return (Criteria) this;
        }

        public Criteria andLoanTimeNotLike(String value) {
            addCriterion("loan_time not like", value, "loanTime");
            return (Criteria) this;
        }

        public Criteria andLoanTimeIn(List<String> values) {
            addCriterion("loan_time in", values, "loanTime");
            return (Criteria) this;
        }

        public Criteria andLoanTimeNotIn(List<String> values) {
            addCriterion("loan_time not in", values, "loanTime");
            return (Criteria) this;
        }

        public Criteria andLoanTimeBetween(String value1, String value2) {
            addCriterion("loan_time between", value1, value2, "loanTime");
            return (Criteria) this;
        }

        public Criteria andLoanTimeNotBetween(String value1, String value2) {
            addCriterion("loan_time not between", value1, value2, "loanTime");
            return (Criteria) this;
        }

        public Criteria andMaxMoneyIsNull() {
            addCriterion("max_money is null");
            return (Criteria) this;
        }

        public Criteria andMaxMoneyIsNotNull() {
            addCriterion("max_money is not null");
            return (Criteria) this;
        }

        public Criteria andMaxMoneyEqualTo(BigDecimal value) {
            addCriterion("max_money =", value, "maxMoney");
            return (Criteria) this;
        }

        public Criteria andMaxMoneyNotEqualTo(BigDecimal value) {
            addCriterion("max_money <>", value, "maxMoney");
            return (Criteria) this;
        }

        public Criteria andMaxMoneyGreaterThan(BigDecimal value) {
            addCriterion("max_money >", value, "maxMoney");
            return (Criteria) this;
        }

        public Criteria andMaxMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("max_money >=", value, "maxMoney");
            return (Criteria) this;
        }

        public Criteria andMaxMoneyLessThan(BigDecimal value) {
            addCriterion("max_money <", value, "maxMoney");
            return (Criteria) this;
        }

        public Criteria andMaxMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("max_money <=", value, "maxMoney");
            return (Criteria) this;
        }

        public Criteria andMaxMoneyIn(List<BigDecimal> values) {
            addCriterion("max_money in", values, "maxMoney");
            return (Criteria) this;
        }

        public Criteria andMaxMoneyNotIn(List<BigDecimal> values) {
            addCriterion("max_money not in", values, "maxMoney");
            return (Criteria) this;
        }

        public Criteria andMaxMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("max_money between", value1, value2, "maxMoney");
            return (Criteria) this;
        }

        public Criteria andMaxMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("max_money not between", value1, value2, "maxMoney");
            return (Criteria) this;
        }

        public Criteria andMaxLoanIsNull() {
            addCriterion("max_loan is null");
            return (Criteria) this;
        }

        public Criteria andMaxLoanIsNotNull() {
            addCriterion("max_loan is not null");
            return (Criteria) this;
        }

        public Criteria andMaxLoanEqualTo(Integer value) {
            addCriterion("max_loan =", value, "maxLoan");
            return (Criteria) this;
        }

        public Criteria andMaxLoanNotEqualTo(Integer value) {
            addCriterion("max_loan <>", value, "maxLoan");
            return (Criteria) this;
        }

        public Criteria andMaxLoanGreaterThan(Integer value) {
            addCriterion("max_loan >", value, "maxLoan");
            return (Criteria) this;
        }

        public Criteria andMaxLoanGreaterThanOrEqualTo(Integer value) {
            addCriterion("max_loan >=", value, "maxLoan");
            return (Criteria) this;
        }

        public Criteria andMaxLoanLessThan(Integer value) {
            addCriterion("max_loan <", value, "maxLoan");
            return (Criteria) this;
        }

        public Criteria andMaxLoanLessThanOrEqualTo(Integer value) {
            addCriterion("max_loan <=", value, "maxLoan");
            return (Criteria) this;
        }

        public Criteria andMaxLoanIn(List<Integer> values) {
            addCriterion("max_loan in", values, "maxLoan");
            return (Criteria) this;
        }

        public Criteria andMaxLoanNotIn(List<Integer> values) {
            addCriterion("max_loan not in", values, "maxLoan");
            return (Criteria) this;
        }

        public Criteria andMaxLoanBetween(Integer value1, Integer value2) {
            addCriterion("max_loan between", value1, value2, "maxLoan");
            return (Criteria) this;
        }

        public Criteria andMaxLoanNotBetween(Integer value1, Integer value2) {
            addCriterion("max_loan not between", value1, value2, "maxLoan");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNull() {
            addCriterion("priority is null");
            return (Criteria) this;
        }

        public Criteria andPriorityIsNotNull() {
            addCriterion("priority is not null");
            return (Criteria) this;
        }

        public Criteria andPriorityEqualTo(BigDecimal value) {
            addCriterion("priority =", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotEqualTo(BigDecimal value) {
            addCriterion("priority <>", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThan(BigDecimal value) {
            addCriterion("priority >", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("priority >=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThan(BigDecimal value) {
            addCriterion("priority <", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityLessThanOrEqualTo(BigDecimal value) {
            addCriterion("priority <=", value, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityIn(List<BigDecimal> values) {
            addCriterion("priority in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotIn(List<BigDecimal> values) {
            addCriterion("priority not in", values, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("priority between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andPriorityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("priority not between", value1, value2, "priority");
            return (Criteria) this;
        }

        public Criteria andDropWithdrawTimeIsNull() {
            addCriterion("drop_withdraw_time is null");
            return (Criteria) this;
        }

        public Criteria andDropWithdrawTimeIsNotNull() {
            addCriterion("drop_withdraw_time is not null");
            return (Criteria) this;
        }

        public Criteria andDropWithdrawTimeEqualTo(String value) {
            addCriterion("drop_withdraw_time =", value, "dropWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andDropWithdrawTimeNotEqualTo(String value) {
            addCriterion("drop_withdraw_time <>", value, "dropWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andDropWithdrawTimeGreaterThan(String value) {
            addCriterion("drop_withdraw_time >", value, "dropWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andDropWithdrawTimeGreaterThanOrEqualTo(String value) {
            addCriterion("drop_withdraw_time >=", value, "dropWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andDropWithdrawTimeLessThan(String value) {
            addCriterion("drop_withdraw_time <", value, "dropWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andDropWithdrawTimeLessThanOrEqualTo(String value) {
            addCriterion("drop_withdraw_time <=", value, "dropWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andDropWithdrawTimeLike(String value) {
            addCriterion("drop_withdraw_time like", value, "dropWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andDropWithdrawTimeNotLike(String value) {
            addCriterion("drop_withdraw_time not like", value, "dropWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andDropWithdrawTimeIn(List<String> values) {
            addCriterion("drop_withdraw_time in", values, "dropWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andDropWithdrawTimeNotIn(List<String> values) {
            addCriterion("drop_withdraw_time not in", values, "dropWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andDropWithdrawTimeBetween(String value1, String value2) {
            addCriterion("drop_withdraw_time between", value1, value2, "dropWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andDropWithdrawTimeNotBetween(String value1, String value2) {
            addCriterion("drop_withdraw_time not between", value1, value2, "dropWithdrawTime");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeRuleIsNull() {
            addCriterion("withdraw_time_rule is null");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeRuleIsNotNull() {
            addCriterion("withdraw_time_rule is not null");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeRuleEqualTo(String value) {
            addCriterion("withdraw_time_rule =", value, "withdrawTimeRule");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeRuleNotEqualTo(String value) {
            addCriterion("withdraw_time_rule <>", value, "withdrawTimeRule");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeRuleGreaterThan(String value) {
            addCriterion("withdraw_time_rule >", value, "withdrawTimeRule");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeRuleGreaterThanOrEqualTo(String value) {
            addCriterion("withdraw_time_rule >=", value, "withdrawTimeRule");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeRuleLessThan(String value) {
            addCriterion("withdraw_time_rule <", value, "withdrawTimeRule");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeRuleLessThanOrEqualTo(String value) {
            addCriterion("withdraw_time_rule <=", value, "withdrawTimeRule");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeRuleLike(String value) {
            addCriterion("withdraw_time_rule like", value, "withdrawTimeRule");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeRuleNotLike(String value) {
            addCriterion("withdraw_time_rule not like", value, "withdrawTimeRule");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeRuleIn(List<String> values) {
            addCriterion("withdraw_time_rule in", values, "withdrawTimeRule");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeRuleNotIn(List<String> values) {
            addCriterion("withdraw_time_rule not in", values, "withdrawTimeRule");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeRuleBetween(String value1, String value2) {
            addCriterion("withdraw_time_rule between", value1, value2, "withdrawTimeRule");
            return (Criteria) this;
        }

        public Criteria andWithdrawTimeRuleNotBetween(String value1, String value2) {
            addCriterion("withdraw_time_rule not between", value1, value2, "withdrawTimeRule");
            return (Criteria) this;
        }

        public Criteria andNeedWithdrawIsNull() {
            addCriterion("need_withdraw is null");
            return (Criteria) this;
        }

        public Criteria andNeedWithdrawIsNotNull() {
            addCriterion("need_withdraw is not null");
            return (Criteria) this;
        }

        public Criteria andNeedWithdrawEqualTo(Integer value) {
            addCriterion("need_withdraw =", value, "needWithdraw");
            return (Criteria) this;
        }

        public Criteria andNeedWithdrawNotEqualTo(Integer value) {
            addCriterion("need_withdraw <>", value, "needWithdraw");
            return (Criteria) this;
        }

        public Criteria andNeedWithdrawGreaterThan(Integer value) {
            addCriterion("need_withdraw >", value, "needWithdraw");
            return (Criteria) this;
        }

        public Criteria andNeedWithdrawGreaterThanOrEqualTo(Integer value) {
            addCriterion("need_withdraw >=", value, "needWithdraw");
            return (Criteria) this;
        }

        public Criteria andNeedWithdrawLessThan(Integer value) {
            addCriterion("need_withdraw <", value, "needWithdraw");
            return (Criteria) this;
        }

        public Criteria andNeedWithdrawLessThanOrEqualTo(Integer value) {
            addCriterion("need_withdraw <=", value, "needWithdraw");
            return (Criteria) this;
        }

        public Criteria andNeedWithdrawIn(List<Integer> values) {
            addCriterion("need_withdraw in", values, "needWithdraw");
            return (Criteria) this;
        }

        public Criteria andNeedWithdrawNotIn(List<Integer> values) {
            addCriterion("need_withdraw not in", values, "needWithdraw");
            return (Criteria) this;
        }

        public Criteria andNeedWithdrawBetween(Integer value1, Integer value2) {
            addCriterion("need_withdraw between", value1, value2, "needWithdraw");
            return (Criteria) this;
        }

        public Criteria andNeedWithdrawNotBetween(Integer value1, Integer value2) {
            addCriterion("need_withdraw not between", value1, value2, "needWithdraw");
            return (Criteria) this;
        }

        public Criteria andAllotSwitchIsNull() {
            addCriterion("allot_switch is null");
            return (Criteria) this;
        }

        public Criteria andAllotSwitchIsNotNull() {
            addCriterion("allot_switch is not null");
            return (Criteria) this;
        }

        public Criteria andAllotSwitchEqualTo(Integer value) {
            addCriterion("allot_switch =", value, "allotSwitch");
            return (Criteria) this;
        }

        public Criteria andAllotSwitchNotEqualTo(Integer value) {
            addCriterion("allot_switch <>", value, "allotSwitch");
            return (Criteria) this;
        }

        public Criteria andAllotSwitchGreaterThan(Integer value) {
            addCriterion("allot_switch >", value, "allotSwitch");
            return (Criteria) this;
        }

        public Criteria andAllotSwitchGreaterThanOrEqualTo(Integer value) {
            addCriterion("allot_switch >=", value, "allotSwitch");
            return (Criteria) this;
        }

        public Criteria andAllotSwitchLessThan(Integer value) {
            addCriterion("allot_switch <", value, "allotSwitch");
            return (Criteria) this;
        }

        public Criteria andAllotSwitchLessThanOrEqualTo(Integer value) {
            addCriterion("allot_switch <=", value, "allotSwitch");
            return (Criteria) this;
        }

        public Criteria andAllotSwitchIn(List<Integer> values) {
            addCriterion("allot_switch in", values, "allotSwitch");
            return (Criteria) this;
        }

        public Criteria andAllotSwitchNotIn(List<Integer> values) {
            addCriterion("allot_switch not in", values, "allotSwitch");
            return (Criteria) this;
        }

        public Criteria andAllotSwitchBetween(Integer value1, Integer value2) {
            addCriterion("allot_switch between", value1, value2, "allotSwitch");
            return (Criteria) this;
        }

        public Criteria andAllotSwitchNotBetween(Integer value1, Integer value2) {
            addCriterion("allot_switch not between", value1, value2, "allotSwitch");
            return (Criteria) this;
        }

        public Criteria andPushSwitchIsNull() {
            addCriterion("push_switch is null");
            return (Criteria) this;
        }

        public Criteria andPushSwitchIsNotNull() {
            addCriterion("push_switch is not null");
            return (Criteria) this;
        }

        public Criteria andPushSwitchEqualTo(Integer value) {
            addCriterion("push_switch =", value, "pushSwitch");
            return (Criteria) this;
        }

        public Criteria andPushSwitchNotEqualTo(Integer value) {
            addCriterion("push_switch <>", value, "pushSwitch");
            return (Criteria) this;
        }

        public Criteria andPushSwitchGreaterThan(Integer value) {
            addCriterion("push_switch >", value, "pushSwitch");
            return (Criteria) this;
        }

        public Criteria andPushSwitchGreaterThanOrEqualTo(Integer value) {
            addCriterion("push_switch >=", value, "pushSwitch");
            return (Criteria) this;
        }

        public Criteria andPushSwitchLessThan(Integer value) {
            addCriterion("push_switch <", value, "pushSwitch");
            return (Criteria) this;
        }

        public Criteria andPushSwitchLessThanOrEqualTo(Integer value) {
            addCriterion("push_switch <=", value, "pushSwitch");
            return (Criteria) this;
        }

        public Criteria andPushSwitchIn(List<Integer> values) {
            addCriterion("push_switch in", values, "pushSwitch");
            return (Criteria) this;
        }

        public Criteria andPushSwitchNotIn(List<Integer> values) {
            addCriterion("push_switch not in", values, "pushSwitch");
            return (Criteria) this;
        }

        public Criteria andPushSwitchBetween(Integer value1, Integer value2) {
            addCriterion("push_switch between", value1, value2, "pushSwitch");
            return (Criteria) this;
        }

        public Criteria andPushSwitchNotBetween(Integer value1, Integer value2) {
            addCriterion("push_switch not between", value1, value2, "pushSwitch");
            return (Criteria) this;
        }

        public Criteria andQuerySwitchIsNull() {
            addCriterion("query_switch is null");
            return (Criteria) this;
        }

        public Criteria andQuerySwitchIsNotNull() {
            addCriterion("query_switch is not null");
            return (Criteria) this;
        }

        public Criteria andQuerySwitchEqualTo(Integer value) {
            addCriterion("query_switch =", value, "querySwitch");
            return (Criteria) this;
        }

        public Criteria andQuerySwitchNotEqualTo(Integer value) {
            addCriterion("query_switch <>", value, "querySwitch");
            return (Criteria) this;
        }

        public Criteria andQuerySwitchGreaterThan(Integer value) {
            addCriterion("query_switch >", value, "querySwitch");
            return (Criteria) this;
        }

        public Criteria andQuerySwitchGreaterThanOrEqualTo(Integer value) {
            addCriterion("query_switch >=", value, "querySwitch");
            return (Criteria) this;
        }

        public Criteria andQuerySwitchLessThan(Integer value) {
            addCriterion("query_switch <", value, "querySwitch");
            return (Criteria) this;
        }

        public Criteria andQuerySwitchLessThanOrEqualTo(Integer value) {
            addCriterion("query_switch <=", value, "querySwitch");
            return (Criteria) this;
        }

        public Criteria andQuerySwitchIn(List<Integer> values) {
            addCriterion("query_switch in", values, "querySwitch");
            return (Criteria) this;
        }

        public Criteria andQuerySwitchNotIn(List<Integer> values) {
            addCriterion("query_switch not in", values, "querySwitch");
            return (Criteria) this;
        }

        public Criteria andQuerySwitchBetween(Integer value1, Integer value2) {
            addCriterion("query_switch between", value1, value2, "querySwitch");
            return (Criteria) this;
        }

        public Criteria andQuerySwitchNotBetween(Integer value1, Integer value2) {
            addCriterion("query_switch not between", value1, value2, "querySwitch");
            return (Criteria) this;
        }

        public Criteria andWeekendSwitchIsNull() {
            addCriterion("weekend_switch is null");
            return (Criteria) this;
        }

        public Criteria andWeekendSwitchIsNotNull() {
            addCriterion("weekend_switch is not null");
            return (Criteria) this;
        }

        public Criteria andWeekendSwitchEqualTo(Integer value) {
            addCriterion("weekend_switch =", value, "weekendSwitch");
            return (Criteria) this;
        }

        public Criteria andWeekendSwitchNotEqualTo(Integer value) {
            addCriterion("weekend_switch <>", value, "weekendSwitch");
            return (Criteria) this;
        }

        public Criteria andWeekendSwitchGreaterThan(Integer value) {
            addCriterion("weekend_switch >", value, "weekendSwitch");
            return (Criteria) this;
        }

        public Criteria andWeekendSwitchGreaterThanOrEqualTo(Integer value) {
            addCriterion("weekend_switch >=", value, "weekendSwitch");
            return (Criteria) this;
        }

        public Criteria andWeekendSwitchLessThan(Integer value) {
            addCriterion("weekend_switch <", value, "weekendSwitch");
            return (Criteria) this;
        }

        public Criteria andWeekendSwitchLessThanOrEqualTo(Integer value) {
            addCriterion("weekend_switch <=", value, "weekendSwitch");
            return (Criteria) this;
        }

        public Criteria andWeekendSwitchIn(List<Integer> values) {
            addCriterion("weekend_switch in", values, "weekendSwitch");
            return (Criteria) this;
        }

        public Criteria andWeekendSwitchNotIn(List<Integer> values) {
            addCriterion("weekend_switch not in", values, "weekendSwitch");
            return (Criteria) this;
        }

        public Criteria andWeekendSwitchBetween(Integer value1, Integer value2) {
            addCriterion("weekend_switch between", value1, value2, "weekendSwitch");
            return (Criteria) this;
        }

        public Criteria andWeekendSwitchNotBetween(Integer value1, Integer value2) {
            addCriterion("weekend_switch not between", value1, value2, "weekendSwitch");
            return (Criteria) this;
        }

        public Criteria andOpenAccountSwitchIsNull() {
            addCriterion("open_account_switch is null");
            return (Criteria) this;
        }

        public Criteria andOpenAccountSwitchIsNotNull() {
            addCriterion("open_account_switch is not null");
            return (Criteria) this;
        }

        public Criteria andOpenAccountSwitchEqualTo(Integer value) {
            addCriterion("open_account_switch =", value, "openAccountSwitch");
            return (Criteria) this;
        }

        public Criteria andOpenAccountSwitchNotEqualTo(Integer value) {
            addCriterion("open_account_switch <>", value, "openAccountSwitch");
            return (Criteria) this;
        }

        public Criteria andOpenAccountSwitchGreaterThan(Integer value) {
            addCriterion("open_account_switch >", value, "openAccountSwitch");
            return (Criteria) this;
        }

        public Criteria andOpenAccountSwitchGreaterThanOrEqualTo(Integer value) {
            addCriterion("open_account_switch >=", value, "openAccountSwitch");
            return (Criteria) this;
        }

        public Criteria andOpenAccountSwitchLessThan(Integer value) {
            addCriterion("open_account_switch <", value, "openAccountSwitch");
            return (Criteria) this;
        }

        public Criteria andOpenAccountSwitchLessThanOrEqualTo(Integer value) {
            addCriterion("open_account_switch <=", value, "openAccountSwitch");
            return (Criteria) this;
        }

        public Criteria andOpenAccountSwitchIn(List<Integer> values) {
            addCriterion("open_account_switch in", values, "openAccountSwitch");
            return (Criteria) this;
        }

        public Criteria andOpenAccountSwitchNotIn(List<Integer> values) {
            addCriterion("open_account_switch not in", values, "openAccountSwitch");
            return (Criteria) this;
        }

        public Criteria andOpenAccountSwitchBetween(Integer value1, Integer value2) {
            addCriterion("open_account_switch between", value1, value2, "openAccountSwitch");
            return (Criteria) this;
        }

        public Criteria andOpenAccountSwitchNotBetween(Integer value1, Integer value2) {
            addCriterion("open_account_switch not between", value1, value2, "openAccountSwitch");
            return (Criteria) this;
        }

        public Criteria andWithdrawSwitchIsNull() {
            addCriterion("withdraw_switch is null");
            return (Criteria) this;
        }

        public Criteria andWithdrawSwitchIsNotNull() {
            addCriterion("withdraw_switch is not null");
            return (Criteria) this;
        }

        public Criteria andWithdrawSwitchEqualTo(Integer value) {
            addCriterion("withdraw_switch =", value, "withdrawSwitch");
            return (Criteria) this;
        }

        public Criteria andWithdrawSwitchNotEqualTo(Integer value) {
            addCriterion("withdraw_switch <>", value, "withdrawSwitch");
            return (Criteria) this;
        }

        public Criteria andWithdrawSwitchGreaterThan(Integer value) {
            addCriterion("withdraw_switch >", value, "withdrawSwitch");
            return (Criteria) this;
        }

        public Criteria andWithdrawSwitchGreaterThanOrEqualTo(Integer value) {
            addCriterion("withdraw_switch >=", value, "withdrawSwitch");
            return (Criteria) this;
        }

        public Criteria andWithdrawSwitchLessThan(Integer value) {
            addCriterion("withdraw_switch <", value, "withdrawSwitch");
            return (Criteria) this;
        }

        public Criteria andWithdrawSwitchLessThanOrEqualTo(Integer value) {
            addCriterion("withdraw_switch <=", value, "withdrawSwitch");
            return (Criteria) this;
        }

        public Criteria andWithdrawSwitchIn(List<Integer> values) {
            addCriterion("withdraw_switch in", values, "withdrawSwitch");
            return (Criteria) this;
        }

        public Criteria andWithdrawSwitchNotIn(List<Integer> values) {
            addCriterion("withdraw_switch not in", values, "withdrawSwitch");
            return (Criteria) this;
        }

        public Criteria andWithdrawSwitchBetween(Integer value1, Integer value2) {
            addCriterion("withdraw_switch between", value1, value2, "withdrawSwitch");
            return (Criteria) this;
        }

        public Criteria andWithdrawSwitchNotBetween(Integer value1, Integer value2) {
            addCriterion("withdraw_switch not between", value1, value2, "withdrawSwitch");
            return (Criteria) this;
        }

        public Criteria andLoanTypeIsNull() {
            addCriterion("loan_type is null");
            return (Criteria) this;
        }

        public Criteria andLoanTypeIsNotNull() {
            addCriterion("loan_type is not null");
            return (Criteria) this;
        }

        public Criteria andLoanTypeEqualTo(String value) {
            addCriterion("loan_type =", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeNotEqualTo(String value) {
            addCriterion("loan_type <>", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeGreaterThan(String value) {
            addCriterion("loan_type >", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeGreaterThanOrEqualTo(String value) {
            addCriterion("loan_type >=", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeLessThan(String value) {
            addCriterion("loan_type <", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeLessThanOrEqualTo(String value) {
            addCriterion("loan_type <=", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeLike(String value) {
            addCriterion("loan_type like", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeNotLike(String value) {
            addCriterion("loan_type not like", value, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeIn(List<String> values) {
            addCriterion("loan_type in", values, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeNotIn(List<String> values) {
            addCriterion("loan_type not in", values, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeBetween(String value1, String value2) {
            addCriterion("loan_type between", value1, value2, "loanType");
            return (Criteria) this;
        }

        public Criteria andLoanTypeNotBetween(String value1, String value2) {
            addCriterion("loan_type not between", value1, value2, "loanType");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIsNull() {
            addCriterion("merchant_id is null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIsNotNull() {
            addCriterion("merchant_id is not null");
            return (Criteria) this;
        }

        public Criteria andMerchantIdEqualTo(String value) {
            addCriterion("merchant_id =", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotEqualTo(String value) {
            addCriterion("merchant_id <>", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdGreaterThan(String value) {
            addCriterion("merchant_id >", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdGreaterThanOrEqualTo(String value) {
            addCriterion("merchant_id >=", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLessThan(String value) {
            addCriterion("merchant_id <", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLessThanOrEqualTo(String value) {
            addCriterion("merchant_id <=", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdLike(String value) {
            addCriterion("merchant_id like", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotLike(String value) {
            addCriterion("merchant_id not like", value, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdIn(List<String> values) {
            addCriterion("merchant_id in", values, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotIn(List<String> values) {
            addCriterion("merchant_id not in", values, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdBetween(String value1, String value2) {
            addCriterion("merchant_id between", value1, value2, "merchantId");
            return (Criteria) this;
        }

        public Criteria andMerchantIdNotBetween(String value1, String value2) {
            addCriterion("merchant_id not between", value1, value2, "merchantId");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(LocalDateTime value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(LocalDateTime value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(LocalDateTime value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<LocalDateTime> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(LocalDateTime value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(LocalDateTime value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(LocalDateTime value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(LocalDateTime value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<LocalDateTime> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<LocalDateTime> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table capitalist
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table capitalist
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}